# Generated by Django 5.1.4 on 2024-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_remove_chaivariety_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(default=None, upload_to='chais/'),
            preserve_default=False,
        ),
    ]
